#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xF3599FF828C67298 (nisse@lysator.liu.se)
#
Name     : compat-nettle-soname7
Version  : 3.5.1
Release  : 44
URL      : https://mirrors.kernel.org/gnu/nettle/nettle-3.5.1.tar.gz
Source0  : https://mirrors.kernel.org/gnu/nettle/nettle-3.5.1.tar.gz
Source1  : https://mirrors.kernel.org/gnu/nettle/nettle-3.5.1.tar.gz.sig
Summary  : Nettle low-level cryptographic library (symmetric algorithms)
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0 LGPL-2.0+ LGPL-3.0
Requires: compat-nettle-soname7-lib = %{version}-%{release}
Requires: compat-nettle-soname7-license = %{version}-%{release}
Requires: p11-kit
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : gmp-dev
BuildRequires : gmp-dev32
BuildRequires : gmp-lib32
BuildRequires : openssl-dev
BuildRequires : p11-kit
BuildRequires : texinfo
BuildRequires : valgrind-dev

%description
What is GNU Nettle? A quote from the introduction in the Nettle Manual:
Nettle is a cryptographic library that is designed to fit easily in more
or less any context: In crypto toolkits for object-oriented languages
(C++, Python, Pike, ...), in applications like LSH or GNUPG, or even in
kernel space. In most contexts, you need more than the basic
cryptographic algorithms, you also need some way to keep track of available
algorithms, their properties and variants. You often have some algorithm
selection process, often dictated by a protocol you want to implement.

And as the requirements of applications differ in subtle and not so
subtle ways, an API that fits one application well can be a pain to use
in a different context. And that is why there are so many different
cryptographic libraries around.

Nettle tries to avoid this problem by doing one thing, the low-level
crypto stuff, and providing a simple but general interface to it.
In particular, Nettle doesn't do algorithm selection. It doesn't do
memory allocation. It doesn't do any I/O.

The idea is that one can build several application and context specific
interfaces on top of Nettle, and share the code, test cases, benchmarks,
documentation, etc. Examples are the Nettle module for the Pike
language, and LSH, which both use an object-oriented abstraction on top
of the library.

%package lib
Summary: lib components for the compat-nettle-soname7 package.
Group: Libraries
Requires: compat-nettle-soname7-license = %{version}-%{release}

%description lib
lib components for the compat-nettle-soname7 package.


%package lib32
Summary: lib32 components for the compat-nettle-soname7 package.
Group: Default
Requires: compat-nettle-soname7-license = %{version}-%{release}

%description lib32
lib32 components for the compat-nettle-soname7 package.


%package license
Summary: license components for the compat-nettle-soname7 package.
Group: Default

%description license
license components for the compat-nettle-soname7 package.


%prep
%setup -q -n nettle-3.5.1
cd %{_builddir}/nettle-3.5.1
pushd ..
cp -a nettle-3.5.1 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1588306211
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FCFLAGS="$FFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FFLAGS="$FFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
%configure --disable-static --disable-openssl --enable-shared --enable-static  --enable-x86-aesni
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32 -mstackrealign"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32 -mstackrealign"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32 -mstackrealign"
%configure --disable-static --disable-openssl --enable-shared --enable-static  --enable-x86-aesni   --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make -C testsuite check
#make -C ../buildavx2/testsuite check
make -C ../build32/testsuite check

%install
export SOURCE_DATE_EPOCH=1588306211
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-nettle-soname7
cp %{_builddir}/nettle-3.5.1/COPYING.LESSERv3 %{buildroot}/usr/share/package-licenses/compat-nettle-soname7/e7d563f52bf5295e6dba1d67ac23e9f6a160fab9
cp %{_builddir}/nettle-3.5.1/COPYINGv2 %{buildroot}/usr/share/package-licenses/compat-nettle-soname7/4cc77b90af91e615a64ae04893fdffa7939db84c
cp %{_builddir}/nettle-3.5.1/COPYINGv3 %{buildroot}/usr/share/package-licenses/compat-nettle-soname7/e88f6aea9379eb98a7bbea965fc7127a64b41ad9
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install
## Remove excluded files
rm -f %{buildroot}/usr/bin/nettle-hash
rm -f %{buildroot}/usr/bin/nettle-lfib-stream
rm -f %{buildroot}/usr/bin/pkcs1-conv
rm -f %{buildroot}/usr/bin/sexp-conv
rm -f %{buildroot}/usr/bin/nettle-pbkdf2
rm -f %{buildroot}/usr/include/nettle/aes.h
rm -f %{buildroot}/usr/include/nettle/arcfour.h
rm -f %{buildroot}/usr/include/nettle/arctwo.h
rm -f %{buildroot}/usr/include/nettle/asn1.h
rm -f %{buildroot}/usr/include/nettle/base16.h
rm -f %{buildroot}/usr/include/nettle/base64.h
rm -f %{buildroot}/usr/include/nettle/bignum.h
rm -f %{buildroot}/usr/include/nettle/blowfish.h
rm -f %{buildroot}/usr/include/nettle/buffer.h
rm -f %{buildroot}/usr/include/nettle/camellia.h
rm -f %{buildroot}/usr/include/nettle/cast128.h
rm -f %{buildroot}/usr/include/nettle/cbc.h
rm -f %{buildroot}/usr/include/nettle/ccm.h
rm -f %{buildroot}/usr/include/nettle/cfb.h
rm -f %{buildroot}/usr/include/nettle/chacha-poly1305.h
rm -f %{buildroot}/usr/include/nettle/chacha.h
rm -f %{buildroot}/usr/include/nettle/cmac.h
rm -f %{buildroot}/usr/include/nettle/ctr.h
rm -f %{buildroot}/usr/include/nettle/curve25519.h
rm -f %{buildroot}/usr/include/nettle/des.h
rm -f %{buildroot}/usr/include/nettle/dsa-compat.h
rm -f %{buildroot}/usr/include/nettle/dsa.h
rm -f %{buildroot}/usr/include/nettle/eax.h
rm -f %{buildroot}/usr/include/nettle/ecc-curve.h
rm -f %{buildroot}/usr/include/nettle/ecc.h
rm -f %{buildroot}/usr/include/nettle/ecdsa.h
rm -f %{buildroot}/usr/include/nettle/eddsa.h
rm -f %{buildroot}/usr/include/nettle/gcm.h
rm -f %{buildroot}/usr/include/nettle/gosthash94.h
rm -f %{buildroot}/usr/include/nettle/hkdf.h
rm -f %{buildroot}/usr/include/nettle/hmac.h
rm -f %{buildroot}/usr/include/nettle/knuth-lfib.h
rm -f %{buildroot}/usr/include/nettle/macros.h
rm -f %{buildroot}/usr/include/nettle/md2.h
rm -f %{buildroot}/usr/include/nettle/md4.h
rm -f %{buildroot}/usr/include/nettle/md5-compat.h
rm -f %{buildroot}/usr/include/nettle/md5.h
rm -f %{buildroot}/usr/include/nettle/memops.h
rm -f %{buildroot}/usr/include/nettle/memxor.h
rm -f %{buildroot}/usr/include/nettle/nettle-meta.h
rm -f %{buildroot}/usr/include/nettle/nettle-types.h
rm -f %{buildroot}/usr/include/nettle/pbkdf2.h
rm -f %{buildroot}/usr/include/nettle/pgp.h
rm -f %{buildroot}/usr/include/nettle/pkcs1.h
rm -f %{buildroot}/usr/include/nettle/poly1305.h
rm -f %{buildroot}/usr/include/nettle/pss-mgf1.h
rm -f %{buildroot}/usr/include/nettle/pss.h
rm -f %{buildroot}/usr/include/nettle/realloc.h
rm -f %{buildroot}/usr/include/nettle/ripemd160.h
rm -f %{buildroot}/usr/include/nettle/rsa.h
rm -f %{buildroot}/usr/include/nettle/salsa20.h
rm -f %{buildroot}/usr/include/nettle/serpent.h
rm -f %{buildroot}/usr/include/nettle/sexp.h
rm -f %{buildroot}/usr/include/nettle/sha.h
rm -f %{buildroot}/usr/include/nettle/sha1.h
rm -f %{buildroot}/usr/include/nettle/sha2.h
rm -f %{buildroot}/usr/include/nettle/sha3.h
rm -f %{buildroot}/usr/include/nettle/twofish.h
rm -f %{buildroot}/usr/include/nettle/umac.h
rm -f %{buildroot}/usr/include/nettle/version.h
rm -f %{buildroot}/usr/include/nettle/xts.h
rm -f %{buildroot}/usr/include/nettle/yarrow.h
rm -f %{buildroot}/usr/lib32/libhogweed.so
rm -f %{buildroot}/usr/lib32/libnettle.so
rm -f %{buildroot}/usr/lib32/pkgconfig/32hogweed.pc
rm -f %{buildroot}/usr/lib32/pkgconfig/32nettle.pc
rm -f %{buildroot}/usr/lib32/pkgconfig/hogweed.pc
rm -f %{buildroot}/usr/lib32/pkgconfig/nettle.pc
rm -f %{buildroot}/usr/lib64/libhogweed.so
rm -f %{buildroot}/usr/lib64/libnettle.so
rm -f %{buildroot}/usr/lib64/pkgconfig/hogweed.pc
rm -f %{buildroot}/usr/lib64/pkgconfig/nettle.pc
rm -f %{buildroot}/usr/share/info/nettle.info

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/libhogweed.so.5
/usr/lib64/libhogweed.so.5.0
/usr/lib64/libnettle.so.7
/usr/lib64/libnettle.so.7.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libhogweed.so.5
/usr/lib32/libhogweed.so.5.0
/usr/lib32/libnettle.so.7
/usr/lib32/libnettle.so.7.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-nettle-soname7/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/compat-nettle-soname7/e7d563f52bf5295e6dba1d67ac23e9f6a160fab9
/usr/share/package-licenses/compat-nettle-soname7/e88f6aea9379eb98a7bbea965fc7127a64b41ad9
